# 项目svn配置
svn:
    # svn起始版本号
    revStart: 305113
    # svn截止版本号（不填默认最新）
    revEnd: 309439
    # svn路径
    path: https://192.169.1.81/svn/cmmi/04javaemp/01dev/05code/emp_branches/emp_7.2.0.452m_linux
# emp配置
emp:
    # 编译输出路径
    outPutPath:
# copyList配置
copy-list:
    # 生成路径（默认jar同级目录下）
    path: C:\Users\ZHANG\Desktop\copylist.txt
    # 前缀（默认为emp_sta）
    prefix: emp_sta