# 项目svn配置
svn:
    # svn起始版本号
    revStart: 273630
    # svn截止版本号（不填默认最新）
    revEnd: 311054
    # svn路径
    path: https://192.169.1.81/svn/cmmi/04javaemp/01dev/05code/emp_branches/emp_7.2.0.452m_linux
    # 显示原始svn记录
    showRecord: false
# emp配置
emp:
    # 编译输出路径
    outPutPath: E:\mw_out\emp_tg_72\web
# copyList配置
copy-list:
    # 生成路径（默认jar同级目录下）
    path:
    # 前缀（默认为emp_sta）
    prefix: