# 项目svn配置【配置项冒号后面要有个空格！！！】
svn:
    # 【必填】svn起始版本号
    revStart: 310719
    # 【必填】svn路径
    path: https://192.169.1.81/svn/cmmi/04javaemp/01dev/05code/emp_branches/emp_7.2.0.452m_linux
    # 版本标识文件（svn结束版本号为本机svn账户修改的最后一个版本号）
    versionFile: WebRoot\init.txt
# emp配置
emp:
    # 【必填】源码路径（用于过滤文件夹）
    sourcePath: E:\mw_projects\20190801-emp_7.2.0.452m_linux
    # 【必填】编译输出路径（用于获取内部类）
    outPutPath: E:\mw_out\emp_tg_72\web

# slf4j配置
logging:
  pattern:
    console: '%d{MM-dd HH:mm:ss} %-5level [%thread] %logger{15} - %msg%n'