#【配置项冒号后面要有个空格！！！】
#【文件拼接功能，常用于将SQL脚本拼接到一个文件里面】
file-splicer:
    # 是否启用该功能
    enable: false
    # 【必填】文件夹路径
    path: E:\mw_project_new\umc_git\umc_sql\UMC_V3.6\mysql\全新脚本
    # 【必填】生成文件名称或路径
    gen-file-name: G:\Users\ZYJ\Desktop\umc-mysql36.sql
    # 文件名白名单模式，多个以逗号分隔
    whitePattern: .*sql
    # 文件名黑名单模式，多个以逗号分隔
    blackPattern: 000.*
    # 生成文件之前，在path文件夹路径执行的cmd命令（如更新git或者svn）
#    command: git pull upstream dev
    command:

# 【文件重命名功能，常用于新建类似目录，但文件名仅通过替换即可】
file-rename:
    # 是否启用该功能
    enable: false
    # 【必填】文件夹路径
    path: E:\mw_project_new\umc_git\umc_sql\UMC_V3.6
    # 目标文件夹路径
    targetPath: G:\Users\ZYJ\Desktop\UMC_V3.7
    # 【必填】替换关键字
    replaceWords: [{word: "3.6", newWord: "3.7"}, {word: "3.5", newWord: "3.6"}]

#【生成copyList功能】
copy-list-maker:
    # 是否启用该功能
    enable: false
    # 【必填】svn起始版本号
    svn:
        rev-start: 309780
        # svn截止版本号（不填默认最新版本号）
        rev-end:
        # 【必填】svn路径
        path: https://192.169.1.81/svn/cmmi/04javaemp/01dev/05code/02branches/stable-6.9(m)/emp
    emp:
        # 【必填】emp web项目编译路径（用于内部类检测，idea中Project Structure -> Artifacts中Output directory值）
        output-path: E:\mw_out\emp_tg_win69\web

#【网络检测功能】
network-checker:
    # 是否启用该功能
    enable: false
    # 【必填】定时校验时间间隔(单位：秒)
    # wifi名称（断网重连）
    wifiName: YJ&YR
    corn: 0 */1 * * * ?

#【定时刷新hosts】
host-refresher:
    # 是否启用该功能
    enable: false
    # 网络hosts文件
    hosts: [{name: "github", url: "https://cdn.jsdelivr.net/gh/521xueweihan/GitHub520@main/hosts"}]
    # 定时器corn
    corn: "*/20 * * * * ?"
    # 本地hosts文件地址
    hosts-path: G:\Windows\System32\drivers\etc\hosts

#【文件关键字替换】
properties-replace:
    # 是否启用该功能
    enable: true
    # 替换关键字描述
    replaceKeys: [
        {
              filePaths: [
                  E:\mw_project_new\umc_git\umc-portal2\system\src\main\resources\bootstrap.properties,
                  E:\mw_project_new\umc_git\umc-portal2\system\src\main\resources\application-dev.properties
              ],
              propertiesMap: {
                "server.addr":"192.169.7.13",
                "montnets.outerUrl":"http://192.169.7.13:9777/umc/",
                "server.port":"9777",
                "emp.corptype":"0",
                "video.encoder.system":"Windows",
                "montnets.emp.nginx.url":"http://192.169.7.13:8008",
                # 数据库信息
                "emp.database.type":"mysql",
                "emp.database.ip":"192.169.7.102",
                "emp.database.port":"3306",
                "emp.database.name":"umc310",
                "spring.datasource.druid.username":"root",
                "spring.datasource.druid.password":"ENC(s9tSvduQ9LOiLl6v48Y6ag==)",
                "spring.datasource.druid.url":"jdbc:mysql://${emp.database.ip}:${emp.database.port}/${emp.database.name}?useUnicode=true&useSSL=false&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true",
                "spring.datasource.druid.driver-class-name":"com.mysql.cj.jdbc.Driver",
                # redis
                "spring.redis.cluster.nodes":"192.169.6.157:7003,192.169.6.157:7004,192.169.6.157:7005",
                "spring.redis.cluster.max-redirects":"3",
                # 定时
                "cluster.iscluster":"1",
                "cluster.isruntimejob":"1",
                "timer.callback.enable":"false",
                # 文件服务器
                "file.server.ip":"192.169.7.106",
                "file.server.port":"8080",
              },
              uselessProperties: [
                "spring.cloud.nacos.config.server-addr",
                "spring.redis.host",
                "spring.redis.port"
              ]

        }
    ]


