# 【命令执行功能】
cmd-executor:
    # 是否启用该功能
    enable: false
    # 命令执行路径，相当于在以下路径打开cmd
#    base-dir: E:\mw_project_new\umc_git\umc-portal-refactoring
    base-dir: E:\mw_project_new\umc_git\umc-portal-refactoring2
    # 执行编码，避免日志输出乱码
    charset: "gbk"
    # 命令文件
    cmd-file-path: E:\mw_project_new\zhangyj\zhangyuejia\tools\build\cmd.txt

# 多模块代码更新
multi-module-pull-code:
  # 是否开启该功能
  enable: false
  # 启用id
  enableRefId: [
    "dev",
#    "dev-spfee",
  ]
  # 日志错误关键词（判断是否命令是否成功执行）
  error-log-words: "abort,error,fail,unable,Could not"
  # 模块参数
  modules-properties: [
      {
          refId: "dev",
        # 远程仓库名称
          remote-repo-name: "upstream",
        # 项目路径
#          project-path: E:\mw_project_new\umc_git\umc-portal-refactoring,
          project-path: E:\mw_project_new\umc_git\umc-portal-refactoring2,
        # 是否需要切换到本地分支
          enable-checkout-localbranch: true,
        # 模块参数
          modules-params: [
          {
              name: "umc-portal",
            # 本地分支
              local-branch: "umc-3.12-refactoring",
            # 远程分支
              remote-branch: "umc-3.12-refactoring"
          },
          {
              name: "umc-portal-audit",
            # 本地分支
              local-branch: "dev",
            # 远程分支
              remote-branch: "dev"
          },
          {
              name: "umc-portal-boot",
            # 本地分支
              local-branch: "dev",
            # 远程分支
              remote-branch: "dev"
          },
          {
              name: "umc-portal-business",
            # 本地分支
              local-branch: "dev",
            # 远程分支
              remote-branch: "dev"
          },
          {
              name: "umc-portal-common",
            # 本地分支
              local-branch: "dev",
            # 远程分支
              remote-branch: "dev"
          },
          {
              name: "umc-portal-communication",
            # 本地分支
              local-branch: "dev",
            # 远程分支
              remote-branch: "dev"
          },
          {
              name: "umc-portal-dependencies",
            # 本地分支
              local-branch: "dev",
            # 远程分支
              remote-branch: "dev"
          },
          {
              name: "umc-portal-system",
            # 本地分支
              local-branch: "dev",
            # 远程分支
              remote-branch: "dev"
          },
          {
              name: "umc-portal-utils",
            # 本地分支
              local-branch: "dev",
            # 远程分支
              remote-branch: "dev"
          }
          ]
      },
    {
      refId: "dev-spfee",
      # 远程仓库名称
      remote-repo-name: "origin",
      # 项目路径
      project-path: E:\mw_project_new\umc_git\umc-refactoring3,
      # 是否需要切换到本地分支
      enable-checkout-localbranch: true,
      # 模块参数
      modules-params: [
        {
          name: "umc-portal",
          # 本地分支
          local-branch: "dev-spfee",
          # 远程分支
          remote-branch: "umc-3.12-refactoring,dev-spfee"
        },
        {
          name: "umc-portal-audit",
          # 本地分支
          local-branch: "dev",
          # 远程分支
          remote-branch: "dev"
        },
        {
          name: "umc-portal-boot",
          # 本地分支
          local-branch: "dev",
          # 远程分支
          remote-branch: "dev"
        },
        {
          name: "umc-portal-business",
          # 本地分支
          local-branch: "dev",
          # 远程分支
          remote-branch: "dev"
        },
        {
          name: "umc-portal-common",
          # 本地分支
          local-branch: "dev-spfee",
          # 远程分支
          remote-branch: "dev-spfee,dev"
        },
        {
          name: "umc-portal-communication",
          # 本地分支
          local-branch: "dev",
          # 远程分支
          remote-branch: "dev"
        },
        {
          name: "umc-portal-dependencies",
          # 本地分支
          local-branch: "dev",
          # 远程分支
          remote-branch: "dev"
        },
        {
          name: "umc-portal-system",
          # 本地分支
          local-branch: "dev",
          # 远程分支
          remote-branch: "dev"
        },
        {
          name: "umc-portal-utils",
          # 本地分支
          local-branch: "dev",
          # 远程分支
          remote-branch: "dev"
        }
      ]
    }
  ]



