filePath: E:\mw_project_new\zhangyj\zhangyuejia\cmd-executor\boot\src\main\resources\component\file\exec-file.sh
# 命令执行路径，相当于在以下路径打开cmd
dir: E:\mw_project_new\umc_git\umc-portal-refactoring
# 执行编码，避免日志输出乱码
charset: "gbk"