# 启用id
enableRefId: [
    "umc3.13",
]
# 日志错误关键词（判断是否命令是否成功执行）
errorLogWords: ["abort", "error", "fail", "unable", "Could not"]
# 模块参数
modulesProperties: [
{
    refId: "umc3.13",
    # 远程仓库名称
    remoteRepoName: "upstream",
    # 项目根目录，此处可以为空，为空会被替换为 cmd-executor.dir
    dir:
    # 是否需要切换到本地分支
    enableCheckoutLocalBranch: true,
    # 模块参数
    modulesParams: [
    {
        name: "umc-portal",
        # 本地分支
        localBranch: "umc-3.12-refactoring",
        # 远程分支
        remoteBranch: ["umc-3.12-refactoring"]
    },
    {
        name: "umc-portal-audit",
        # 本地分支
        localBranch: "dev",
        # 远程分支
        remoteBranch: ["dev"]
    },
    {
        name: "umc-portal-boot",
        # 本地分支
        localBranch: "dev",
        # 远程分支
        remoteBranch: ["dev"]
    },
    {
        name: "umc-portal-business",
        # 本地分支
        localBranch: "dev",
        # 远程分支
        remoteBranch: ["dev"]
    },
    {
        name: "umc-portal-common",
        # 本地分支
        localBranch: "dev",
        # 远程分支
        remoteBranch: ["dev"]
    },
    {
        name: "umc-portal-communication",
        # 本地分支
        localBranch: "dev",
        # 远程分支
        remoteBranch: ["dev"]
    },
    {
        name: "umc-portal-dependencies",
        # 本地分支
        localBranch: "dev",
        # 远程分支
        remoteBranch: ["dev"]
    },
    {
        name: "umc-portal-system",
        # 本地分支
        localBranch: "dev",
        # 远程分支
        remoteBranch: ["dev"]
    },
    {
        name: "umc-portal-utils",
        # 本地分支
        localBranch: "dev",
        # 远程分支
        remoteBranch: ["dev"]
    }
    ]
}
]



