# 本地pdf文件地址
#pdfPaths: [E:\个人\出差报销\202303出差报销\发票\滴滴出行行程报销单A (1).pdf,
#           E:\个人\出差报销\202303出差报销\发票\【高德打车-30.00元-1个行程】高德打车电子行程单.pdf,
#           E:\个人\出差报销\202303出差报销\发票\滴滴出行行程报销单B (1).pdf]

#pdfPaths: [D:\test\滴滴出行行程报销单.pdf,D:\test\滴滴出行行程报销单(1)_4-5.pdf]
pdfDir: E:\个人\出差报销\202304出差报销\行程单

docOutPath: D:\test\1.docx
