# 行程单pdf目录（支持高德和滴滴）
pdfDir: C:/Users/zhanglj/Downloads/滴滴出行行程报销单（1）.pdf
# 市内交通word输出地址
docOutPath: E:\个人\出差报销\202308出差报销\交通明细-章乐佳.docx
# 参数
params: {"myName": "章乐佳", "peopleNum": "2","peopleName": "肖祥成","reason": "宁德出差",}