# 【文件重命名功能，常用于新建类似目录，但文件名仅通过替换即可】
file-rename:
  # 是否启用该功能
  enable: false
  # 【必填】文件夹路径
  path: E:\mw_project_new\umc_git\umc_sql\UMC_V3.6
  # 目标文件夹路径
  targetPath: G:\Users\ZYJ\Desktop\UMC_V3.7
  # 【必填】替换关键字
  replaceWords: [{word: "3.6", newWord: "3.7"}, {word: "3.5", newWord: "3.6"}]