# 配置文件配置
spring:
  profiles:
    active: copy-list-maker,file-rename,file-splicer,host-refresher,network-checker,print-file-size,properties-replace

tools:
  # 是否检查只有一个功能运行
  checkOneFunction: true

# slf4j配置
logging:
  pattern:
    console: '%d{MM-dd HH:mm:ss} %-5level%msg%n'
  file:
    name: "./app/log/log.log"